-- Lifeline OS initial schema.
--
-- NOTE ON PROVENANCE: this file was hand-written, not generated by
-- `prisma migrate dev`. On the machine this project was built on, the
-- Prisma schema-engine binary (schema-engine-windows.exe) is blocked by a
-- Windows Device Guard / WDAC policy, so `prisma migrate dev`/`db push`
-- cannot run — see docs/architecture.md "Known environment limitation".
-- This SQL is applied directly via better-sqlite3 in prisma/bootstrap.ts
-- for local dev. On any unrestricted machine (Linux CI, Docker, macOS,
-- an unrestricted Windows box) prefer `npx prisma migrate dev`, which will
-- pick up this same migrations/ directory as history going forward.

CREATE TABLE "User" (
  "id" TEXT PRIMARY KEY,
  "email" TEXT NOT NULL UNIQUE,
  "name" TEXT NOT NULL,
  "role" TEXT NOT NULL,
  "passwordHash" TEXT NOT NULL,
  "createdAt" DATETIME NOT NULL
);

CREATE TABLE "Patient" (
  "id" TEXT PRIMARY KEY,
  "mrn" TEXT NOT NULL UNIQUE,
  "name" TEXT NOT NULL,
  "dob" DATETIME NOT NULL,
  "userId" TEXT UNIQUE REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE,
  "createdAt" DATETIME NOT NULL
);

CREATE TABLE "CareJourney" (
  "id" TEXT PRIMARY KEY,
  "patientId" TEXT NOT NULL REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  "title" TEXT NOT NULL,
  "state" TEXT NOT NULL,
  "createdAt" DATETIME NOT NULL,
  "updatedAt" DATETIME NOT NULL
);
CREATE INDEX "CareJourney_patientId_idx" ON "CareJourney"("patientId");

CREATE TABLE "CareEvent" (
  "id" TEXT PRIMARY KEY,
  "patientId" TEXT NOT NULL REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  "journeyId" TEXT NOT NULL REFERENCES "CareJourney"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  "type" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "description" TEXT,
  "occurredAt" DATETIME NOT NULL,
  "createdAt" DATETIME NOT NULL,
  "createdById" TEXT REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE,
  "metadata" TEXT
);
CREATE INDEX "CareEvent_patientId_idx" ON "CareEvent"("patientId");
CREATE INDEX "CareEvent_journeyId_idx" ON "CareEvent"("journeyId");

CREATE TABLE "CareObligation" (
  "id" TEXT PRIMARY KEY,
  "patientId" TEXT NOT NULL REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  "journeyId" TEXT NOT NULL REFERENCES "CareJourney"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  "sourceEventId" TEXT NOT NULL REFERENCES "CareEvent"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  "type" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "priority" TEXT NOT NULL,
  "createdAt" DATETIME NOT NULL,
  "dueAt" DATETIME NOT NULL,
  "status" TEXT NOT NULL,
  "assignedToId" TEXT REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE,
  "completedAt" DATETIME,
  "evidence" TEXT
);
CREATE INDEX "CareObligation_patientId_idx" ON "CareObligation"("patientId");
CREATE INDEX "CareObligation_journeyId_idx" ON "CareObligation"("journeyId");
CREATE INDEX "CareObligation_status_idx" ON "CareObligation"("status");

CREATE TABLE "Referral" (
  "id" TEXT PRIMARY KEY,
  "patientId" TEXT NOT NULL REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  "journeyId" TEXT NOT NULL REFERENCES "CareJourney"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  "specialty" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "createdById" TEXT REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE,
  "createdAt" DATETIME NOT NULL,
  "notes" TEXT
);
CREATE INDEX "Referral_patientId_idx" ON "Referral"("patientId");

CREATE TABLE "Appointment" (
  "id" TEXT PRIMARY KEY,
  "patientId" TEXT NOT NULL REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  "journeyId" TEXT NOT NULL REFERENCES "CareJourney"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  "referralId" TEXT REFERENCES "Referral"("id") ON DELETE SET NULL ON UPDATE CASCADE,
  "type" TEXT NOT NULL,
  "provider" TEXT NOT NULL,
  "scheduledAt" DATETIME NOT NULL,
  "status" TEXT NOT NULL,
  "createdAt" DATETIME NOT NULL
);
CREATE INDEX "Appointment_patientId_idx" ON "Appointment"("patientId");

CREATE TABLE "Task" (
  "id" TEXT PRIMARY KEY,
  "patientId" TEXT NOT NULL REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  "journeyId" TEXT NOT NULL REFERENCES "CareJourney"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  "obligationId" TEXT REFERENCES "CareObligation"("id") ON DELETE SET NULL ON UPDATE CASCADE,
  "title" TEXT NOT NULL,
  "description" TEXT,
  "assignedToId" TEXT REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE,
  "assignedRole" TEXT,
  "priority" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "dueAt" DATETIME,
  "createdAt" DATETIME NOT NULL,
  "completedAt" DATETIME,
  "version" INTEGER NOT NULL DEFAULT 1
);
CREATE INDEX "Task_patientId_idx" ON "Task"("patientId");
CREATE INDEX "Task_status_idx" ON "Task"("status");

CREATE TABLE "Document" (
  "id" TEXT PRIMARY KEY,
  "patientId" TEXT NOT NULL REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  "journeyId" TEXT REFERENCES "CareJourney"("id") ON DELETE SET NULL ON UPDATE CASCADE,
  "filename" TEXT NOT NULL,
  "docType" TEXT,
  "uploadedById" TEXT REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE,
  "uploadedAt" DATETIME NOT NULL,
  "status" TEXT NOT NULL,
  "rawTextSanitized" TEXT,
  "extractedFields" TEXT
);
CREATE INDEX "Document_patientId_idx" ON "Document"("patientId");

CREATE TABLE "RiskAssessment" (
  "id" TEXT PRIMARY KEY,
  "patientId" TEXT NOT NULL REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  "journeyId" TEXT NOT NULL REFERENCES "CareJourney"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  "riskScore" INTEGER NOT NULL,
  "riskLevel" TEXT NOT NULL,
  "factors" TEXT NOT NULL,
  "computedAt" DATETIME NOT NULL
);
CREATE INDEX "RiskAssessment_patientId_idx" ON "RiskAssessment"("patientId");
CREATE INDEX "RiskAssessment_journeyId_idx" ON "RiskAssessment"("journeyId");

CREATE TABLE "AIRecommendation" (
  "id" TEXT PRIMARY KEY,
  "patientId" TEXT NOT NULL REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  "journeyId" TEXT REFERENCES "CareJourney"("id") ON DELETE SET NULL ON UPDATE CASCADE,
  "obligationId" TEXT REFERENCES "CareObligation"("id") ON DELETE SET NULL ON UPDATE CASCADE,
  "agentType" TEXT NOT NULL,
  "recommendation" TEXT NOT NULL,
  "reasoning" TEXT NOT NULL,
  "evidence" TEXT NOT NULL,
  "confidence" REAL NOT NULL,
  "status" TEXT NOT NULL,
  "createdAt" DATETIME NOT NULL,
  "decidedById" TEXT REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE,
  "decidedAt" DATETIME,
  "decisionNotes" TEXT,
  "provider" TEXT,
  "model" TEXT
);
CREATE INDEX "AIRecommendation_patientId_idx" ON "AIRecommendation"("patientId");
CREATE INDEX "AIRecommendation_status_idx" ON "AIRecommendation"("status");

CREATE TABLE "AuditEvent" (
  "id" TEXT PRIMARY KEY,
  "actorId" TEXT REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE,
  "actorRole" TEXT,
  "action" TEXT NOT NULL,
  "entityType" TEXT NOT NULL,
  "entityId" TEXT NOT NULL,
  "previousState" TEXT,
  "newState" TEXT,
  "reason" TEXT,
  "requestId" TEXT NOT NULL,
  "createdAt" DATETIME NOT NULL,
  "careEventId" TEXT REFERENCES "CareEvent"("id") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX "AuditEvent_entityType_entityId_idx" ON "AuditEvent"("entityType", "entityId");
CREATE INDEX "AuditEvent_createdAt_idx" ON "AuditEvent"("createdAt");

CREATE TABLE "SyncOperation" (
  "id" TEXT PRIMARY KEY,
  "operationId" TEXT NOT NULL UNIQUE,
  "userId" TEXT REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE,
  "entityType" TEXT NOT NULL,
  "entityId" TEXT NOT NULL,
  "operationType" TEXT NOT NULL,
  "payload" TEXT NOT NULL,
  "createdAt" DATETIME NOT NULL,
  "appliedAt" DATETIME,
  "syncStatus" TEXT NOT NULL,
  "conflictDetails" TEXT
);
CREATE INDEX "SyncOperation_entityType_entityId_idx" ON "SyncOperation"("entityType", "entityId");

CREATE TABLE "Notification" (
  "id" TEXT PRIMARY KEY,
  "userId" TEXT NOT NULL REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  "title" TEXT NOT NULL,
  "body" TEXT NOT NULL,
  "type" TEXT NOT NULL,
  "read" BOOLEAN NOT NULL DEFAULT 0,
  "createdAt" DATETIME NOT NULL,
  "relatedEntityType" TEXT,
  "relatedEntityId" TEXT
);
CREATE INDEX "Notification_userId_idx" ON "Notification"("userId");
