import { db } from "@/lib/db";
import { EmptyState } from "@/components/ui/primitives";
import { RecommendationCard } from "@/components/dashboard/RecommendationCard";

export default async function RecommendationsPage() {
  const recommendations = await db.aIRecommendation.findMany({
    orderBy: { createdAt: "desc" },
    include: { patient: { select: { name: true } } },
    take: 100,
  });

  return (
    <div className="space-y-4">
      <div>
        <h1 className="text-lg font-semibold text-foreground">AI Recommendations</h1>
        <p className="text-sm text-muted">
          Full history of every recommendation generated by Lifeline OS&apos;s agents, including decisions already made.
        </p>
      </div>

      {recommendations.length === 0 ? (
        <EmptyState title="No recommendations yet" />
      ) : (
        <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
          {recommendations.map((r) => (
            <RecommendationCard
              key={r.id}
              redirectTo="/recommendations"
              rec={{
                id: r.id,
                patientName: r.patient.name,
                agentType: r.agentType,
                recommendation: r.recommendation,
                reasoning: r.reasoning,
                evidence: JSON.parse(r.evidence),
                confidence: r.confidence,
                status: r.status,
                provider: r.provider,
                model: r.model,
                createdAt: r.createdAt.toISOString(),
                decisionNotes: r.decisionNotes,
              }}
            />
          ))}
        </div>
      )}
    </div>
  );
}
