import { db } from "@/lib/db";
import { getLatestRisk } from "@/lib/services/risk";
import { Card, CardHeader, CardTitle, CardBody, RiskBadge, EmptyState } from "@/components/ui/primitives";
import { RiskRefreshButton } from "@/components/dashboard/RiskRefreshButton";
import { RiskFactor } from "@/domain/risk-engine";
import { formatDateTime } from "@/lib/format";

export default async function PatientRiskPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const risk = await getLatestRisk(id);
  const explanation = await db.aIRecommendation.findFirst({
    where: { patientId: id, agentType: "RISK_EXPLANATION" },
    orderBy: { createdAt: "desc" },
  });

  const factors: RiskFactor[] = risk ? JSON.parse(risk.factors) : [];

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <p className="text-sm text-muted">
          Computed by a deterministic, configurable rules engine — never an opaque model output.
        </p>
        <RiskRefreshButton patientId={id} />
      </div>

      {!risk ? (
        <EmptyState title="No risk assessment yet" description="Recompute to generate one from current data." />
      ) : (
        <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
          <Card>
            <CardHeader className="flex items-center justify-between">
              <CardTitle>Continuity Risk</CardTitle>
              <RiskBadge level={risk.riskLevel} />
            </CardHeader>
            <CardBody>
              <p className="text-3xl font-semibold text-foreground">{risk.riskScore}/100</p>
              <p className="mt-1 text-xs text-muted">Computed {formatDateTime(risk.computedAt)}</p>

              {factors.length === 0 ? (
                <p className="mt-4 text-sm text-muted">No active risk factors.</p>
              ) : (
                <ul className="mt-4 space-y-2">
                  {factors.map((f, i) => (
                    <li key={i} className="flex items-center justify-between text-sm">
                      <span className="text-foreground">{f.factor}</span>
                      <span className="font-mono text-xs text-muted">+{f.weight}</span>
                    </li>
                  ))}
                </ul>
              )}
            </CardBody>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>AI Explanation</CardTitle>
            </CardHeader>
            <CardBody className="space-y-3 text-sm">
              {!explanation ? (
                <p className="text-muted">No explanation generated yet for the current assessment.</p>
              ) : (
                <>
                  <div>
                    <p className="text-xs font-semibold uppercase tracking-wide text-muted">Why</p>
                    <p className="mt-1 text-foreground">{explanation.reasoning}</p>
                  </div>
                  <div>
                    <p className="text-xs font-semibold uppercase tracking-wide text-muted">Recommended action</p>
                    <p className="mt-1 text-foreground">{explanation.recommendation}</p>
                  </div>
                  <div>
                    <p className="text-xs font-semibold uppercase tracking-wide text-muted">Confidence</p>
                    <p className="mt-1 text-foreground">{Math.round(explanation.confidence * 100)}%</p>
                  </div>
                  <div>
                    <p className="text-xs font-semibold uppercase tracking-wide text-muted">Status</p>
                    <p className="mt-1 text-foreground">
                      {explanation.status === "SUGGESTED" ? "Awaiting approval" : explanation.status}
                    </p>
                  </div>
                  <p className="text-xs text-muted">Generated by {explanation.provider ?? "unknown"} ({explanation.model ?? "n/a"})</p>
                </>
              )}
            </CardBody>
          </Card>
        </div>
      )}
    </div>
  );
}
