import { AIProvider, CompletionRequest, CompletionResult } from "../provider";
import { parseStructuredPrompt } from "../prompt";

/**
 * Deterministic fallback provider. Requires no API key and never makes a
 * network call, so Lifeline OS is fully usable with zero configuration
 * (spec section 12/34). It reads the same TASK/DATA envelope real
 * providers receive and produces grounded, template-based JSON — never
 * inventing facts not present in DATA.
 */
export class MockProvider implements AIProvider {
  readonly name = "mock";
  readonly isConfigured = true;

  async complete(request: CompletionRequest): Promise<CompletionResult> {
    const { task, data } = parseStructuredPrompt(request.prompt);
    const text = renderTask(task, data);
    return { text, provider: this.name, model: "lifeline-deterministic-template-v1" };
  }
}

function renderTask(task: string, data: Record<string, unknown>): string {
  switch (task) {
    case "timeline_summary":
      return JSON.stringify(renderTimelineSummary(data));
    case "continuity_gaps":
      return JSON.stringify(renderContinuityGaps(data));
    case "risk_explanation":
      return JSON.stringify(renderRiskExplanation(data));
    case "coordination_actions":
      return JSON.stringify(renderCoordinationActions(data));
    case "communication_draft":
      return JSON.stringify(renderCommunicationDraft(data));
    case "clinical_summary":
      return JSON.stringify(renderClinicalSummary(data));
    case "document_extraction":
      return JSON.stringify(renderDocumentExtraction(data));
    default:
      return JSON.stringify({ note: `No mock template for task "${task}".` });
  }
}

interface EventLike {
  title: string;
  type: string;
  status: string;
  occurredAt: string;
}

function renderTimelineSummary(data: Record<string, unknown>) {
  const events = (data.events as EventLike[] | undefined) ?? [];
  const keyEvents = events.slice(0, 10).map((e) => `${e.occurredAt}: ${e.title} (${e.status})`);
  const summary =
    events.length > 0
      ? `Patient has ${events.length} recorded event${events.length === 1 ? "" : "s"}, most recently "${
          events[0]?.title
        }". This is a template summary generated by the deterministic mock AI provider (no LLM configured).`
      : "No events recorded yet for this patient.";
  return { summary, keyEvents };
}

interface ObligationLike {
  description: string;
  status: string;
  dueAt: string;
  id: string;
}

function renderContinuityGaps(data: Record<string, unknown>) {
  const obligations = (data.openObligations as ObligationLike[] | undefined) ?? [];
  const overdue = obligations.filter((o) => o.status === "OVERDUE");
  const gaps = overdue.map((o) => ({
    description: `"${o.description}" is overdue (was due ${o.dueAt}) and has not been completed.`,
    relatedObligationId: o.id,
  }));
  const overallAssessment =
    gaps.length > 0
      ? `${gaps.length} continuity gap${gaps.length === 1 ? "" : "s"} detected from overdue obligations.`
      : "No continuity gaps detected from current obligations.";
  return { gaps, overallAssessment };
}

function renderRiskExplanation(data: Record<string, unknown>) {
  const factors = (data.factors as { factor: string; weight: number }[] | undefined) ?? [];
  const riskLevel = (data.riskLevel as string) ?? "UNKNOWN";
  const riskScore = (data.riskScore as number) ?? 0;
  const factorList = factors.map((f) => `${f.factor} (+${f.weight})`).join("; ");
  const explanation =
    factors.length > 0
      ? `This patient's continuity risk is ${riskLevel} (score ${riskScore}/100) because of: ${factorList}.`
      : `This patient's continuity risk is ${riskLevel} (score ${riskScore}/100). No active risk factors were found.`;
  const topFactor = factors[0]?.factor;
  const recommendedAction = topFactor
    ? `Address the highest-weighted factor first: ${topFactor}.`
    : "No immediate action required; continue routine monitoring.";
  return { explanation, recommendedAction };
}

function renderCoordinationActions(data: Record<string, unknown>) {
  const obligations = (data.openObligations as ObligationLike[] | undefined) ?? [];
  const actions = obligations.slice(0, 5).map((o) => ({
    action: `Follow up on: ${o.description}`,
    rationale: `Obligation is ${o.status.toLowerCase()} and due ${o.dueAt}.`,
    priority: o.status === "OVERDUE" ? "HIGH" : "MEDIUM",
  }));
  return { actions };
}

function renderCommunicationDraft(data: Record<string, unknown>) {
  const patientName = (data.patientName as string) ?? "the patient";
  const purpose = (data.purpose as string) ?? "a care coordination matter";
  return {
    subject: `Regarding your care: ${purpose}`,
    body: `Hello ${patientName},\n\nThis is a message from your care team regarding: ${purpose}.\nPlease reach out at your convenience so we can help you stay on track.\n\n[AI-generated draft — requires review before sending.]`,
    channel: "PORTAL_MESSAGE",
  };
}

function renderClinicalSummary(data: Record<string, unknown>) {
  const events = (data.events as EventLike[] | undefined) ?? [];
  const obligations = (data.openObligations as ObligationLike[] | undefined) ?? [];
  const completed = events.filter((e) => e.status === "COMPLETED").map((e) => e.title);
  const pending = events.filter((e) => e.status !== "COMPLETED").map((e) => e.title);
  return {
    currentSituation: `Patient has ${events.length} recorded event(s) and ${obligations.length} open obligation(s).`,
    completedActions: completed,
    pendingActions: pending,
    outstandingObligations: obligations.map((o) => o.description),
    potentialBlockers: obligations.filter((o) => o.status === "OVERDUE").map((o) => o.description),
    questionsForClinician:
      obligations.length > 0
        ? ["Should any overdue obligations be escalated or cancelled?"]
        : [],
  };
}

function renderDocumentExtraction(data: Record<string, unknown>) {
  const text = (data.rawText as string) ?? "";
  return {
    documentType: "UNKNOWN",
    provider: null,
    date: null,
    patientIdentifierText: null,
    followUpRequired: /follow[\s-]?up/i.test(text),
    summary: text.slice(0, 200) || "No text content provided.",
  };
}
